[2024-04-17T14:49:07.979+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: eksplorasi_data_ingest.extract scheduled__2024-04-16T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-04-17T14:52:52.229+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: eksplorasi_data_ingest.extract scheduled__2024-04-16T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
