[2024-04-15T15:30:52.429+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: hello_airflow_dag.mkdir_our_work scheduled__2024-04-14T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
