[2024-04-15T15:30:52.054+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: hello_airflow_dag.mkdir_about_us scheduled__2024-04-14T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
