[2024-04-14T19:07:12.860+0000] {processor.py:161} INFO - Started process (PID=600) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:07:12.864+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:07:12.868+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:07:12.868+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:07:12.915+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:07:12.906+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:07:12.920+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:07:12.967+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.118 seconds
[2024-04-14T19:07:43.171+0000] {processor.py:161} INFO - Started process (PID=660) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:07:43.173+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:07:43.185+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:07:43.184+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:07:43.207+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:07:43.198+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:07:43.209+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:07:43.287+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.121 seconds
[2024-04-14T19:08:13.695+0000] {processor.py:161} INFO - Started process (PID=720) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:08:13.714+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:08:13.721+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:08:13.720+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:08:13.811+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:08:13.805+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:08:13.813+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:08:13.859+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.171 seconds
[2024-04-14T19:08:14.008+0000] {processor.py:161} INFO - Started process (PID=723) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:08:14.010+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:08:14.012+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:08:14.011+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:08:14.059+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:08:14.052+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:08:14.064+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:08:14.086+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.086 seconds
[2024-04-14T19:08:44.160+0000] {processor.py:161} INFO - Started process (PID=781) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:08:44.162+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:08:44.163+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:08:44.162+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:08:44.185+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:08:44.175+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:08:44.199+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:08:44.247+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.095 seconds
[2024-04-14T19:09:14.661+0000] {processor.py:161} INFO - Started process (PID=838) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:09:14.662+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:09:14.663+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:09:14.663+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:09:14.678+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:09:14.674+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:09:14.679+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:09:14.704+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.051 seconds
[2024-04-14T19:09:47.654+0000] {processor.py:161} INFO - Started process (PID=895) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:09:47.655+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:09:47.656+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:09:47.656+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:09:47.844+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:09:47.672+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:09:47.846+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:09:48.146+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.499 seconds
[2024-04-14T19:10:18.205+0000] {processor.py:161} INFO - Started process (PID=953) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:10:18.206+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:10:18.209+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:10:18.208+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:10:18.225+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:10:18.220+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:10:18.227+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:10:18.248+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.051 seconds
[2024-04-14T19:10:48.875+0000] {processor.py:161} INFO - Started process (PID=1011) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:10:48.876+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:10:48.877+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:10:48.876+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:10:48.894+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:10:48.890+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:10:48.896+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:10:48.919+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.054 seconds
[2024-04-14T19:11:13.678+0000] {processor.py:161} INFO - Started process (PID=1052) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:11:13.679+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:11:13.680+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:11:13.680+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:11:13.708+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:11:13.703+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 13, in <module>
    @dag(default_args=default_args, schedule_interval='@daily', dag_id='generate_sum_check_number_dag')
     ^^^
NameError: name 'dag' is not defined
[2024-04-14T19:11:13.710+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:11:13.731+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.059 seconds
[2024-04-14T19:11:39.017+0000] {processor.py:161} INFO - Started process (PID=1101) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:11:39.018+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:11:39.019+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:11:39.019+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:11:39.053+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:11:39.045+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 13, in <module>
    @dag(default_args=default_args, schedule_interval='@daily', dag_id='generate_sum_check_number_dag')
     ^^^
NameError: name 'dag' is not defined
[2024-04-14T19:11:39.055+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:11:39.091+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.084 seconds
[2024-04-14T19:11:55.835+0000] {processor.py:161} INFO - Started process (PID=1144) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:11:55.837+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:11:55.838+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:11:55.838+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:11:55.863+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:11:55.858+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 5, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:11:55.865+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:11:56.114+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.285 seconds
[2024-04-14T19:12:26.893+0000] {processor.py:161} INFO - Started process (PID=1204) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:12:26.895+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:12:26.897+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:12:26.896+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:12:26.952+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:12:26.910+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 5, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:12:26.953+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:12:26.980+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.096 seconds
[2024-04-14T19:12:57.472+0000] {processor.py:161} INFO - Started process (PID=1264) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:12:57.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:12:57.475+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:12:57.475+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:12:57.494+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:12:57.490+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 5, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:12:57.496+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:12:57.526+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.061 seconds
[2024-04-14T19:13:27.822+0000] {processor.py:161} INFO - Started process (PID=1325) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:13:27.824+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:13:27.825+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:13:27.824+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:13:27.849+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:13:27.842+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 5, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:13:27.853+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:13:27.895+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.083 seconds
[2024-04-14T19:13:58.831+0000] {processor.py:161} INFO - Started process (PID=1385) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:13:58.832+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:13:58.834+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:13:58.833+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:13:58.848+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:13:58.844+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 5, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:13:58.850+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:13:58.882+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.059 seconds
[2024-04-14T19:14:29.792+0000] {processor.py:161} INFO - Started process (PID=1446) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:14:29.794+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:14:29.795+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:14:29.795+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:14:29.814+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:14:29.809+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 5, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:14:29.816+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:14:29.839+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.057 seconds
[2024-04-14T19:15:00.377+0000] {processor.py:161} INFO - Started process (PID=1506) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:15:00.378+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:15:00.379+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:15:00.378+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:15:00.431+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:15:00.389+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 5, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:15:00.433+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:15:00.454+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.083 seconds
[2024-04-14T19:15:30.749+0000] {processor.py:161} INFO - Started process (PID=1566) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:15:30.750+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:15:30.755+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:15:30.755+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:15:30.806+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:15:30.802+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 5, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:15:30.809+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:15:30.831+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.088 seconds
[2024-04-14T19:16:01.075+0000] {processor.py:161} INFO - Started process (PID=1626) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:16:01.076+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:16:01.077+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:16:01.077+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:16:01.137+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:16:01.093+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 5, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:16:01.138+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:16:01.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.088 seconds
[2024-04-14T19:16:31.529+0000] {processor.py:161} INFO - Started process (PID=1686) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:16:31.530+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:16:31.532+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:16:31.532+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:16:31.550+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:16:31.546+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 5, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:16:31.551+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:16:31.574+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.051 seconds
[2024-04-14T19:17:02.099+0000] {processor.py:161} INFO - Started process (PID=1746) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:17:02.100+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:17:02.101+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:17:02.101+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:17:02.122+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:17:02.116+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 5, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:17:02.124+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:17:02.147+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.054 seconds
[2024-04-14T19:17:32.724+0000] {processor.py:161} INFO - Started process (PID=1806) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:17:32.725+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:17:32.726+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:17:32.726+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:17:32.746+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:17:32.741+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 5, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:17:32.748+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:17:32.774+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.057 seconds
[2024-04-14T19:18:03.221+0000] {processor.py:161} INFO - Started process (PID=1866) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:18:03.222+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:18:03.223+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:18:03.223+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:18:03.248+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:18:03.245+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 5, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:18:03.250+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:18:03.274+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.062 seconds
[2024-04-14T19:18:33.747+0000] {processor.py:161} INFO - Started process (PID=1926) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:18:33.750+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:18:33.752+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:18:33.752+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:18:33.772+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:18:33.765+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 5, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:18:33.776+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:18:33.818+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.092 seconds
[2024-04-14T19:19:03.952+0000] {processor.py:161} INFO - Started process (PID=1986) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:19:03.954+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:19:03.955+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:19:03.955+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:19:03.984+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:19:03.966+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 5, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:19:03.987+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:19:04.026+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.079 seconds
[2024-04-14T19:19:10.693+0000] {processor.py:161} INFO - Started process (PID=1994) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:19:10.694+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:19:10.696+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:19:10.695+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:19:10.729+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:19:10.725+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 3, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:19:10.732+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:19:10.796+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.113 seconds
[2024-04-14T19:19:40.916+0000] {processor.py:161} INFO - Started process (PID=2054) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:19:40.919+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:19:40.920+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:19:40.920+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:19:40.963+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:19:40.958+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 3, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:19:40.965+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:19:40.985+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.077 seconds
[2024-04-14T19:19:58.162+0000] {processor.py:161} INFO - Started process (PID=2090) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:19:58.163+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:19:58.164+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:19:58.164+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:19:58.183+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:19:58.181+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-04-14T19:19:58.184+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:19:58.208+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.053 seconds
[2024-04-14T19:20:28.831+0000] {processor.py:161} INFO - Started process (PID=2150) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:20:28.858+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:20:28.873+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:20:28.873+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:20:29.310+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:20:29.307+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-04-14T19:20:29.315+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:20:29.367+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.543 seconds
[2024-04-14T19:20:59.766+0000] {processor.py:161} INFO - Started process (PID=2210) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:20:59.767+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:20:59.769+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:20:59.768+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:20:59.793+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:20:59.790+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-04-14T19:20:59.794+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:20:59.819+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.061 seconds
[2024-04-14T19:21:30.027+0000] {processor.py:161} INFO - Started process (PID=2270) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:21:30.029+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:21:30.030+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:21:30.030+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:21:30.051+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:21:30.049+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-04-14T19:21:30.057+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:21:30.108+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.093 seconds
[2024-04-14T19:21:55.524+0000] {processor.py:161} INFO - Started process (PID=2326) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:21:55.525+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:21:55.526+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:21:55.526+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:21:55.553+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:21:55.546+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 3, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:21:55.555+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:21:55.576+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.059 seconds
[2024-04-14T19:22:25.695+0000] {processor.py:161} INFO - Started process (PID=2386) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:22:25.696+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:22:25.698+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:22:25.697+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:22:25.711+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:22:25.707+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 3, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:22:25.713+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:22:25.742+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.055 seconds
[2024-04-14T19:22:56.036+0000] {processor.py:161} INFO - Started process (PID=2443) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:22:56.037+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:22:56.038+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:22:56.038+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:22:56.056+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:22:56.052+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 3, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:22:56.059+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:22:56.081+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.053 seconds
[2024-04-14T19:23:04.905+0000] {processor.py:161} INFO - Started process (PID=2454) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:23:04.907+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:23:04.908+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:23:04.907+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:23:04.937+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:23:04.929+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:23:04.938+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:23:04.981+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.082 seconds
[2024-04-14T19:23:35.383+0000] {processor.py:161} INFO - Started process (PID=2514) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:23:35.385+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:23:35.387+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:23:35.386+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:23:35.451+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:23:35.406+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:23:35.454+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:23:35.475+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.099 seconds
[2024-04-14T19:24:05.779+0000] {processor.py:161} INFO - Started process (PID=2574) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:24:05.781+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:24:05.782+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:24:05.782+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:24:05.797+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:24:05.792+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:24:05.798+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:24:05.820+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.057 seconds
[2024-04-14T19:24:36.087+0000] {processor.py:161} INFO - Started process (PID=2634) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:24:36.088+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:24:36.090+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:24:36.089+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:24:36.115+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:24:36.108+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:24:36.118+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:24:36.143+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.061 seconds
[2024-04-14T19:25:06.274+0000] {processor.py:161} INFO - Started process (PID=2695) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:25:06.275+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:25:06.276+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:25:06.276+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:25:06.306+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:25:06.298+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:25:06.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:25:06.331+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.063 seconds
[2024-04-14T19:25:36.383+0000] {processor.py:161} INFO - Started process (PID=2756) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:25:36.384+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:25:36.386+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:25:36.386+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:25:36.418+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:25:36.411+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:25:36.421+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:25:36.442+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.065 seconds
[2024-04-14T19:26:06.584+0000] {processor.py:161} INFO - Started process (PID=2815) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:26:06.593+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:26:06.595+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:26:06.594+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:26:06.612+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:26:06.605+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:26:06.614+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:26:06.648+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.072 seconds
[2024-04-14T19:26:37.372+0000] {processor.py:161} INFO - Started process (PID=2875) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:26:37.374+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:26:37.375+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:26:37.375+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:26:37.399+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:26:37.392+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:26:37.401+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:26:37.422+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.057 seconds
[2024-04-14T19:27:07.976+0000] {processor.py:161} INFO - Started process (PID=2936) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:27:07.980+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:27:07.982+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:27:07.982+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:27:08.022+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:27:08.005+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:27:08.041+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:27:08.065+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.104 seconds
[2024-04-14T19:27:38.860+0000] {processor.py:161} INFO - Started process (PID=2996) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:27:38.866+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:27:38.868+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:27:38.867+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:27:38.900+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:27:38.892+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:27:38.904+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:27:38.953+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.101 seconds
[2024-04-14T19:28:09.122+0000] {processor.py:161} INFO - Started process (PID=3056) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:28:09.123+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:28:09.124+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:28:09.124+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:28:09.147+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:28:09.142+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:28:09.151+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:28:09.178+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.067 seconds
[2024-04-14T19:28:39.518+0000] {processor.py:161} INFO - Started process (PID=3116) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:28:39.520+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:28:39.521+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:28:39.521+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:28:39.543+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:28:39.537+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:28:39.546+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:28:39.575+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.064 seconds
[2024-04-14T19:29:10.100+0000] {processor.py:161} INFO - Started process (PID=3175) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:29:10.101+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:29:10.103+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:29:10.102+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:29:10.119+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:29:10.115+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:29:10.121+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:29:10.154+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.067 seconds
[2024-04-14T19:29:40.367+0000] {processor.py:161} INFO - Started process (PID=3235) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:29:40.369+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:29:40.370+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:29:40.370+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:29:40.387+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:29:40.381+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:29:40.389+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:29:40.413+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.051 seconds
[2024-04-14T19:30:10.849+0000] {processor.py:161} INFO - Started process (PID=3295) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:30:10.854+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:30:10.861+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:30:10.860+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:30:11.012+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:30:11.007+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:30:11.014+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:30:11.042+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.206 seconds
[2024-04-14T19:30:41.644+0000] {processor.py:161} INFO - Started process (PID=3355) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:30:41.652+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:30:41.654+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:30:41.653+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:30:41.677+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:30:41.671+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:30:41.680+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:30:41.705+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.068 seconds
[2024-04-14T19:31:12.335+0000] {processor.py:161} INFO - Started process (PID=3415) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:31:12.337+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:31:12.339+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:31:12.339+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:31:12.363+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:31:12.355+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:31:12.365+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:31:12.400+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.078 seconds
[2024-04-14T19:31:43.159+0000] {processor.py:161} INFO - Started process (PID=3475) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:31:43.161+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:31:43.163+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:31:43.162+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:31:43.181+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:31:43.177+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:31:43.183+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:31:43.222+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.071 seconds
[2024-04-14T19:32:13.484+0000] {processor.py:161} INFO - Started process (PID=3535) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:32:13.485+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:32:13.487+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:32:13.487+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:32:13.511+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:32:13.506+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:32:13.513+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:32:13.539+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.061 seconds
[2024-04-14T19:32:44.119+0000] {processor.py:161} INFO - Started process (PID=3594) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:32:44.120+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:32:44.122+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:32:44.121+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:32:44.158+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:32:44.141+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:32:44.160+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:32:44.204+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.098 seconds
[2024-04-14T19:33:15.148+0000] {processor.py:161} INFO - Started process (PID=3654) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:33:15.149+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:33:15.151+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:33:15.150+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:33:15.187+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:33:15.173+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:33:15.189+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:33:15.242+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.102 seconds
[2024-04-14T19:33:45.469+0000] {processor.py:161} INFO - Started process (PID=3714) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:33:45.470+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:33:45.473+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:33:45.473+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:33:45.495+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:33:45.486+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:33:45.501+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:33:45.534+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.073 seconds
[2024-04-14T19:34:15.699+0000] {processor.py:161} INFO - Started process (PID=3774) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:34:15.707+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:34:15.709+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:34:15.708+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:34:15.733+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:34:15.728+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:34:15.742+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:34:15.811+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.118 seconds
[2024-04-14T19:34:29.585+0000] {processor.py:161} INFO - Started process (PID=3800) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:34:29.587+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:34:29.588+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:34:29.588+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:34:29.696+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:34:29.689+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag, task
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:34:29.701+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:34:29.747+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.185 seconds
[2024-04-14T19:34:38.427+0000] {processor.py:161} INFO - Started process (PID=3826) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:34:38.429+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:34:38.431+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:34:38.430+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:34:38.459+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:34:38.455+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:34:38.462+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:34:38.512+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.092 seconds
[2024-04-14T19:35:09.183+0000] {processor.py:161} INFO - Started process (PID=3885) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:35:09.199+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:35:09.206+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:35:09.205+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:35:09.664+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:35:09.586+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:35:09.667+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:35:09.736+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.579 seconds
[2024-04-14T19:35:40.397+0000] {processor.py:161} INFO - Started process (PID=3945) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:35:40.401+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:35:40.403+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:35:40.402+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:35:40.511+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:35:40.503+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:35:40.525+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:35:40.598+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.210 seconds
[2024-04-14T19:36:10.799+0000] {processor.py:161} INFO - Started process (PID=4005) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:36:10.801+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:36:10.812+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:36:10.811+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:36:10.843+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:36:10.835+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:36:10.845+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:36:10.880+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.095 seconds
[2024-04-14T19:36:41.068+0000] {processor.py:161} INFO - Started process (PID=4066) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:36:41.074+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:36:41.076+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:36:41.075+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:36:41.106+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:36:41.096+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:36:41.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:36:41.144+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.083 seconds
[2024-04-14T19:37:11.662+0000] {processor.py:161} INFO - Started process (PID=4123) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:37:11.664+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:37:11.665+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:37:11.665+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:37:11.687+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:37:11.681+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:37:11.695+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:37:11.735+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.086 seconds
[2024-04-14T19:37:42.381+0000] {processor.py:161} INFO - Started process (PID=4183) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:37:42.383+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:37:42.384+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:37:42.384+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:37:42.406+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:37:42.401+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:37:42.409+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:37:42.433+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.060 seconds
[2024-04-14T19:38:12.552+0000] {processor.py:161} INFO - Started process (PID=4242) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:38:12.554+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:38:12.555+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:38:12.555+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:38:12.580+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:38:12.568+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:38:12.585+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:38:12.609+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.063 seconds
[2024-04-14T19:38:42.939+0000] {processor.py:161} INFO - Started process (PID=4302) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:38:42.940+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:38:42.941+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:38:42.941+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:38:42.955+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:38:42.950+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:38:42.957+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:38:42.979+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.046 seconds
[2024-04-14T19:39:13.882+0000] {processor.py:161} INFO - Started process (PID=4362) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:39:13.884+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:39:13.886+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:39:13.886+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:39:13.903+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:39:13.897+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:39:13.907+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:39:13.951+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.083 seconds
[2024-04-14T19:39:44.191+0000] {processor.py:161} INFO - Started process (PID=4421) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:39:44.193+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:39:44.196+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:39:44.195+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:39:44.213+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:39:44.207+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:39:44.214+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:39:44.238+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.054 seconds
[2024-04-14T19:40:14.499+0000] {processor.py:161} INFO - Started process (PID=4481) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:40:14.500+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:40:14.501+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:40:14.501+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:40:14.520+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:40:14.515+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:40:14.522+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:40:14.549+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.057 seconds
[2024-04-14T19:40:45.149+0000] {processor.py:161} INFO - Started process (PID=4541) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:40:45.150+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:40:45.151+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:40:45.151+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:40:45.168+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:40:45.163+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:40:45.170+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:40:45.193+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.051 seconds
[2024-04-14T19:41:15.674+0000] {processor.py:161} INFO - Started process (PID=4602) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:41:15.675+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:41:15.676+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:41:15.676+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:41:15.696+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:41:15.688+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:41:15.698+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:41:15.728+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.063 seconds
[2024-04-14T19:41:46.248+0000] {processor.py:161} INFO - Started process (PID=4662) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:41:46.249+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:41:46.251+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:41:46.250+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:41:46.270+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:41:46.265+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:41:46.272+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:41:46.311+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.073 seconds
[2024-04-14T19:42:16.609+0000] {processor.py:161} INFO - Started process (PID=4722) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:42:16.611+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:42:16.612+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:42:16.611+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:42:16.641+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:42:16.630+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:42:16.644+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:42:16.673+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.074 seconds
[2024-04-14T19:42:46.983+0000] {processor.py:161} INFO - Started process (PID=4782) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:42:46.985+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:42:46.987+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:42:46.987+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:42:47.002+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:42:46.996+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:42:47.004+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:42:47.038+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.062 seconds
[2024-04-14T19:43:17.366+0000] {processor.py:161} INFO - Started process (PID=4842) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:43:17.367+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:43:17.368+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:43:17.367+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:43:17.385+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:43:17.377+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:43:17.387+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:43:17.417+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.061 seconds
[2024-04-14T19:43:47.670+0000] {processor.py:161} INFO - Started process (PID=4901) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:43:47.671+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:43:47.673+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:43:47.672+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:43:47.712+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:43:47.703+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:43:47.714+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:43:47.789+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.133 seconds
[2024-04-14T19:44:17.856+0000] {processor.py:161} INFO - Started process (PID=4962) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:44:17.857+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:44:17.858+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:44:17.858+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:44:17.873+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:44:17.867+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:44:17.876+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:44:17.896+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.047 seconds
[2024-04-14T19:44:48.756+0000] {processor.py:161} INFO - Started process (PID=5021) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:44:48.757+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:44:48.758+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:44:48.757+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:44:48.775+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:44:48.771+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:44:48.777+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:44:48.804+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.059 seconds
[2024-04-14T19:45:18.970+0000] {processor.py:161} INFO - Started process (PID=5082) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:45:18.971+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:45:18.972+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:45:18.972+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:45:18.990+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:45:18.985+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:45:18.991+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:45:19.018+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.062 seconds
[2024-04-14T19:45:49.264+0000] {processor.py:161} INFO - Started process (PID=5143) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:45:49.265+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:45:49.267+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:45:49.266+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:45:49.298+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:45:49.283+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:45:49.299+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:45:49.329+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.073 seconds
[2024-04-14T19:46:19.817+0000] {processor.py:161} INFO - Started process (PID=5203) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:46:19.827+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:46:19.830+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:46:19.829+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:46:19.882+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:46:19.876+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:46:19.888+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:46:19.940+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.142 seconds
[2024-04-14T19:46:50.251+0000] {processor.py:161} INFO - Started process (PID=5263) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:46:50.252+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:46:50.254+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:46:50.253+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:46:50.269+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:46:50.261+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:46:50.273+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:46:50.300+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.059 seconds
[2024-04-14T19:47:20.977+0000] {processor.py:161} INFO - Started process (PID=5324) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:47:20.982+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:47:20.984+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:47:20.983+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:47:21.002+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:47:20.993+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:47:21.004+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:47:21.034+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.064 seconds
[2024-04-14T19:47:51.450+0000] {processor.py:161} INFO - Started process (PID=5384) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:47:51.452+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:47:51.453+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:47:51.453+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:47:51.469+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:47:51.466+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:47:51.471+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:47:51.497+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.056 seconds
[2024-04-14T19:48:21.626+0000] {processor.py:161} INFO - Started process (PID=5445) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:48:21.628+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:48:21.629+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:48:21.628+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:48:21.646+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:48:21.638+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:48:21.647+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:48:21.672+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.053 seconds
[2024-04-14T19:48:51.762+0000] {processor.py:161} INFO - Started process (PID=5505) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:48:51.767+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:48:51.781+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:48:51.780+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:48:51.820+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:48:51.811+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:48:51.822+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:48:51.852+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.098 seconds
[2024-04-14T19:49:21.981+0000] {processor.py:161} INFO - Started process (PID=5560) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:49:21.982+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:49:21.983+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:49:21.983+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:49:21.998+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:49:21.993+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:49:22.000+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:49:22.033+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.062 seconds
[2024-04-14T19:49:53.020+0000] {processor.py:161} INFO - Started process (PID=5620) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:49:53.022+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:49:53.024+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:49:53.023+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:49:53.054+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:49:53.040+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:49:53.056+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:49:53.088+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.079 seconds
[2024-04-14T19:50:23.167+0000] {processor.py:161} INFO - Started process (PID=5680) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:50:23.169+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:50:23.171+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:50:23.171+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:50:23.180+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:50:23.178+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:50:23.182+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:50:23.217+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.055 seconds
[2024-04-14T19:50:53.270+0000] {processor.py:161} INFO - Started process (PID=5738) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:50:53.271+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:50:53.272+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:50:53.272+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:50:53.313+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:50:53.307+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:50:53.319+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:50:53.351+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.090 seconds
[2024-04-14T19:51:23.825+0000] {processor.py:161} INFO - Started process (PID=5803) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:51:23.826+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:51:23.828+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:51:23.827+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:51:23.847+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:51:23.842+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:51:23.849+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:51:23.871+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.053 seconds
[2024-04-14T19:51:53.974+0000] {processor.py:161} INFO - Started process (PID=5863) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:51:53.976+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:51:53.978+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:51:53.976+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:51:53.991+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:51:53.987+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:51:53.993+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:51:54.016+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.048 seconds
[2024-04-14T19:52:24.454+0000] {processor.py:161} INFO - Started process (PID=5920) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:52:24.456+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:52:24.457+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:52:24.457+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:52:24.472+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:52:24.466+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:52:24.474+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:52:24.499+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.054 seconds
[2024-04-14T19:52:54.832+0000] {processor.py:161} INFO - Started process (PID=5980) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:52:54.833+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:52:54.835+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:52:54.834+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:52:54.857+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:52:54.849+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:52:54.860+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:52:54.882+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.055 seconds
[2024-04-14T19:53:25.252+0000] {processor.py:161} INFO - Started process (PID=6040) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:53:25.253+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:53:25.254+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:53:25.254+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:53:25.285+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:53:25.267+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:53:25.287+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:53:25.323+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.079 seconds
[2024-04-14T19:54:00.391+0000] {processor.py:161} INFO - Started process (PID=6080) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:54:00.401+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:54:00.413+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:54:00.413+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:54:00.514+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:54:00.473+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:54:00.522+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:54:01.042+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.668 seconds
[2024-04-14T19:54:38.337+0000] {processor.py:161} INFO - Started process (PID=6126) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:54:38.348+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:54:38.350+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:54:38.350+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:54:38.373+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:54:38.366+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:54:38.376+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:54:38.458+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.135 seconds
[2024-04-14T19:55:09.152+0000] {processor.py:161} INFO - Started process (PID=6185) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:55:09.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:55:09.154+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:55:09.153+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:55:09.169+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:55:09.162+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:55:09.171+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:55:09.195+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.051 seconds
[2024-04-14T19:55:39.378+0000] {processor.py:161} INFO - Started process (PID=6245) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:55:39.380+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:55:39.381+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:55:39.381+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:55:39.402+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:55:39.396+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:55:39.404+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:55:39.440+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.070 seconds
[2024-04-14T19:56:10.208+0000] {processor.py:161} INFO - Started process (PID=6305) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:56:10.209+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:56:10.210+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:56:10.210+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:56:10.224+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:56:10.219+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:56:10.226+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:56:10.249+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.049 seconds
[2024-04-14T19:56:40.983+0000] {processor.py:161} INFO - Started process (PID=6365) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:56:40.985+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:56:40.986+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:56:40.985+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:56:41.005+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:56:40.998+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:56:41.007+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:56:41.034+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.059 seconds
[2024-04-14T19:57:11.272+0000] {processor.py:161} INFO - Started process (PID=6423) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:57:11.285+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:57:11.286+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:57:11.286+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:57:11.412+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:57:11.405+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:57:11.415+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:57:11.550+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.286 seconds
[2024-04-14T19:57:41.948+0000] {processor.py:161} INFO - Started process (PID=6483) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:57:41.951+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:57:41.965+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:57:41.964+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:57:42.021+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:57:42.008+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:57:42.023+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:57:42.086+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.146 seconds
[2024-04-14T19:58:18.786+0000] {processor.py:161} INFO - Started process (PID=6538) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:58:18.788+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:58:18.792+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:58:18.791+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:58:18.822+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:58:18.814+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:58:18.824+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:58:18.887+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.114 seconds
[2024-04-14T19:58:48.960+0000] {processor.py:161} INFO - Started process (PID=6597) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:58:48.961+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:58:48.962+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:58:48.962+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:58:48.981+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:58:48.971+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:58:48.983+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:58:49.007+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.058 seconds
[2024-04-14T19:59:19.581+0000] {processor.py:161} INFO - Started process (PID=6656) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:59:19.585+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:59:19.590+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:59:19.586+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:59:19.648+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:59:19.640+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:59:19.652+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:59:20.118+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.562 seconds
[2024-04-14T19:59:55.559+0000] {processor.py:161} INFO - Started process (PID=6727) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:59:55.560+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T19:59:55.562+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:59:55.562+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:59:55.616+0000] {logging_mixin.py:188} INFO - [2024-04-14T19:59:55.595+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T19:59:55.622+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T19:59:55.719+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.172 seconds
[2024-04-14T20:00:25.824+0000] {processor.py:161} INFO - Started process (PID=6780) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T20:00:25.829+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T20:00:25.831+0000] {logging_mixin.py:188} INFO - [2024-04-14T20:00:25.830+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T20:00:25.855+0000] {logging_mixin.py:188} INFO - [2024-04-14T20:00:25.851+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T20:00:25.859+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T20:00:25.885+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.069 seconds
[2024-04-14T20:00:56.723+0000] {processor.py:161} INFO - Started process (PID=6847) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T20:00:56.724+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T20:00:56.726+0000] {logging_mixin.py:188} INFO - [2024-04-14T20:00:56.725+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T20:00:56.745+0000] {logging_mixin.py:188} INFO - [2024-04-14T20:00:56.736+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T20:00:56.747+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T20:00:56.776+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.061 seconds
[2024-04-14T20:01:27.474+0000] {processor.py:161} INFO - Started process (PID=6908) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T20:01:27.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T20:01:27.477+0000] {logging_mixin.py:188} INFO - [2024-04-14T20:01:27.476+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T20:01:27.493+0000] {logging_mixin.py:188} INFO - [2024-04-14T20:01:27.489+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T20:01:27.494+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T20:01:27.537+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.072 seconds
[2024-04-14T20:01:57.923+0000] {processor.py:161} INFO - Started process (PID=6970) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T20:01:57.930+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T20:01:57.935+0000] {logging_mixin.py:188} INFO - [2024-04-14T20:01:57.933+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T20:01:57.954+0000] {logging_mixin.py:188} INFO - [2024-04-14T20:01:57.946+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T20:01:57.958+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T20:01:57.993+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.081 seconds
[2024-04-14T20:02:28.301+0000] {processor.py:161} INFO - Started process (PID=7030) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T20:02:28.302+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T20:02:28.304+0000] {logging_mixin.py:188} INFO - [2024-04-14T20:02:28.303+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T20:02:28.318+0000] {logging_mixin.py:188} INFO - [2024-04-14T20:02:28.314+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T20:02:28.319+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T20:02:28.348+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.055 seconds
[2024-04-14T20:02:58.700+0000] {processor.py:161} INFO - Started process (PID=7091) to work on /opt/airflow/dags/calculator_dag.py
[2024-04-14T20:02:58.702+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/calculator_dag.py for tasks to queue
[2024-04-14T20:02:58.705+0000] {logging_mixin.py:188} INFO - [2024-04-14T20:02:58.702+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/calculator_dag.py
[2024-04-14T20:02:58.726+0000] {logging_mixin.py:188} INFO - [2024-04-14T20:02:58.720+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/calculator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/calculator_dag.py", line 4, in <module>
    from airflow.utils.decorators import dag
ImportError: cannot import name 'dag' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/decorators.py)
[2024-04-14T20:02:58.728+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/calculator_dag.py
[2024-04-14T20:02:58.753+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/calculator_dag.py took 0.069 seconds
