[2024-04-29T15:16:17.913+0000] {processor.py:161} INFO - Started process (PID=1728) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:16:17.915+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:16:17.916+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:16:17.916+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:16:18.521+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:16:17.937+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:16:18.598+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:16:19.352+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 1.446 seconds
[2024-04-29T15:16:50.156+0000] {processor.py:161} INFO - Started process (PID=1790) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:16:50.157+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:16:50.159+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:16:50.158+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:16:50.178+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:16:50.172+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:16:50.179+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:16:50.215+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.067 seconds
[2024-04-29T15:17:20.762+0000] {processor.py:161} INFO - Started process (PID=1849) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:17:20.764+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:17:20.766+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:17:20.766+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:17:20.789+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:17:20.783+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:17:20.790+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:17:20.819+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.069 seconds
[2024-04-29T15:17:51.197+0000] {processor.py:161} INFO - Started process (PID=1908) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:17:51.200+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:17:51.203+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:17:51.202+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:17:51.222+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:17:51.218+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:17:51.224+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:17:51.258+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.068 seconds
[2024-04-29T15:18:21.459+0000] {processor.py:161} INFO - Started process (PID=1967) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:18:21.460+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:18:21.462+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:18:21.462+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:18:21.479+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:18:21.474+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:18:21.481+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:18:21.507+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.055 seconds
[2024-04-29T15:18:52.044+0000] {processor.py:161} INFO - Started process (PID=2026) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:18:52.045+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:18:52.047+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:18:52.047+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:18:52.061+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:18:52.058+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:18:52.063+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:18:52.083+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.046 seconds
[2024-04-29T15:19:22.460+0000] {processor.py:161} INFO - Started process (PID=2086) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:19:22.461+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:19:22.463+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:19:22.463+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:19:22.487+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:19:22.481+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:19:22.489+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:19:22.512+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.063 seconds
[2024-04-29T15:19:52.694+0000] {processor.py:161} INFO - Started process (PID=2145) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:19:52.696+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:19:52.699+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:19:52.698+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:19:52.718+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:19:52.715+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:19:52.720+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:19:52.763+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.079 seconds
[2024-04-29T15:20:23.458+0000] {processor.py:161} INFO - Started process (PID=2204) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:20:23.461+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:20:23.464+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:20:23.463+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:20:23.478+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:20:23.474+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:20:23.479+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:20:23.504+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.055 seconds
[2024-04-29T15:20:54.215+0000] {processor.py:161} INFO - Started process (PID=2263) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:20:54.216+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:20:54.218+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:20:54.218+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:20:54.239+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:20:54.234+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:20:54.242+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:20:54.270+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.064 seconds
[2024-04-29T15:21:24.896+0000] {processor.py:161} INFO - Started process (PID=2322) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:21:24.897+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:21:24.899+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:21:24.899+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:21:24.913+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:21:24.911+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:21:24.914+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:21:24.935+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.045 seconds
[2024-04-29T15:21:55.136+0000] {processor.py:161} INFO - Started process (PID=2381) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:21:55.138+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:21:55.161+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:21:55.155+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:21:55.195+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:21:55.191+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:21:55.197+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:21:55.235+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.110 seconds
[2024-04-29T15:22:25.451+0000] {processor.py:161} INFO - Started process (PID=2440) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:22:25.453+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:22:25.455+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:22:25.455+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:22:25.473+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:22:25.470+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:22:25.475+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:22:25.497+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.053 seconds
[2024-04-29T15:22:28.804+0000] {processor.py:161} INFO - Started process (PID=2445) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:22:28.805+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:22:28.807+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:22:28.807+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:22:28.836+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:22:28.832+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:22:28.838+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:22:28.857+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.064 seconds
[2024-04-29T15:22:34.742+0000] {processor.py:161} INFO - Started process (PID=2455) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:22:34.743+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:22:34.747+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:22:34.746+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:22:34.776+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:22:34.772+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:22:34.778+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:22:34.805+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.071 seconds
[2024-04-29T15:23:04.945+0000] {processor.py:161} INFO - Started process (PID=2513) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:23:04.947+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:23:04.950+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:23:04.950+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:23:04.967+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:23:04.962+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:23:04.968+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:23:05.010+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.073 seconds
[2024-04-29T15:23:35.334+0000] {processor.py:161} INFO - Started process (PID=2568) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:23:35.335+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:23:35.337+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:23:35.337+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:23:35.351+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:23:35.347+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:23:35.353+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:23:35.374+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.046 seconds
[2024-04-29T15:24:05.652+0000] {processor.py:161} INFO - Started process (PID=2627) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:24:05.653+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:24:05.655+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:24:05.655+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:24:05.681+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:24:05.677+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:24:05.682+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:24:05.705+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.059 seconds
[2024-04-29T15:24:36.008+0000] {processor.py:161} INFO - Started process (PID=2686) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:24:36.009+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:24:36.011+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:24:36.011+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:24:36.038+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:24:36.023+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:24:36.045+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:24:36.072+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.073 seconds
[2024-04-29T15:25:06.334+0000] {processor.py:161} INFO - Started process (PID=2745) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:25:06.335+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:25:06.337+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:25:06.337+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:25:06.352+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:25:06.349+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:25:06.353+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:25:06.377+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.049 seconds
[2024-04-29T15:25:37.276+0000] {processor.py:161} INFO - Started process (PID=2804) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:25:37.278+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:25:37.281+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:25:37.281+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:25:37.307+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:25:37.303+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:25:37.309+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:25:37.331+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.065 seconds
[2024-04-29T15:26:07.709+0000] {processor.py:161} INFO - Started process (PID=2863) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:26:07.711+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:26:07.714+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:26:07.713+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:26:07.738+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:26:07.733+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:26:07.739+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:26:07.765+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.068 seconds
[2024-04-29T15:26:37.845+0000] {processor.py:161} INFO - Started process (PID=2922) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:26:37.846+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:26:37.848+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:26:37.848+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:26:37.860+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:26:37.856+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:26:37.861+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:26:37.885+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.046 seconds
[2024-04-29T15:27:08.144+0000] {processor.py:161} INFO - Started process (PID=2978) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:27:08.146+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:27:08.149+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:27:08.148+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:27:08.170+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:27:08.166+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:27:08.172+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:27:08.202+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.082 seconds
[2024-04-29T15:27:23.980+0000] {processor.py:161} INFO - Started process (PID=3021) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:27:23.981+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:27:23.984+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:27:23.983+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:27:24.031+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:27:24.027+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:27:24.046+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:27:24.096+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.125 seconds
[2024-04-29T15:27:37.660+0000] {processor.py:161} INFO - Started process (PID=3038) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:27:37.661+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:27:37.663+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:27:37.663+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:27:37.703+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:27:37.683+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:27:37.704+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:27:37.731+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.081 seconds
[2024-04-29T15:28:05.676+0000] {processor.py:161} INFO - Started process (PID=3095) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:28:05.680+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:28:05.687+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:28:05.686+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:28:05.768+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:28:05.763+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:28:05.769+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:28:05.790+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.131 seconds
[2024-04-29T15:28:36.074+0000] {processor.py:161} INFO - Started process (PID=3154) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:28:36.075+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:28:36.077+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:28:36.077+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:28:36.094+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:28:36.090+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:28:36.096+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:28:36.124+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.057 seconds
[2024-04-29T15:29:06.209+0000] {processor.py:161} INFO - Started process (PID=3213) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:29:06.211+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:29:06.213+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:29:06.213+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:29:06.230+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:29:06.226+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:29:06.232+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:29:06.255+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.052 seconds
[2024-04-29T15:29:36.400+0000] {processor.py:161} INFO - Started process (PID=3271) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:29:36.402+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:29:36.404+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:29:36.404+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:29:36.426+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:29:36.422+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:29:36.430+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:29:36.458+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.065 seconds
[2024-04-29T15:29:46.710+0000] {processor.py:161} INFO - Started process (PID=3294) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:29:46.711+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:29:46.713+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:29:46.713+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:29:46.738+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:29:46.735+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 5, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:29:46.739+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:29:46.760+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.055 seconds
[2024-04-29T15:30:17.130+0000] {processor.py:161} INFO - Started process (PID=3353) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:30:17.131+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:30:17.134+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:30:17.133+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:30:17.148+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:30:17.145+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 5, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:30:17.149+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:30:17.168+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.044 seconds
[2024-04-29T15:30:26.715+0000] {processor.py:161} INFO - Started process (PID=3376) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:30:26.715+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:30:26.717+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:30:26.717+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:30:26.738+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:30:26.734+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:30:26.739+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:30:26.759+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.051 seconds
[2024-04-29T15:30:29.843+0000] {processor.py:161} INFO - Started process (PID=3379) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:30:29.844+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:30:29.847+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:30:29.847+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:30:29.886+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:30:29.881+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:30:29.888+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:30:29.924+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.092 seconds
[2024-04-29T15:30:31.793+0000] {processor.py:161} INFO - Started process (PID=3382) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:30:31.826+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:30:31.864+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:30:31.863+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:30:32.208+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:30:32.186+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:30:32.214+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:30:32.248+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.475 seconds
[2024-04-29T15:30:33.024+0000] {processor.py:161} INFO - Started process (PID=3383) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:30:33.025+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:30:33.031+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:30:33.029+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:30:33.125+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:30:33.120+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:30:33.127+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:30:33.188+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.171 seconds
[2024-04-29T15:30:34.247+0000] {processor.py:161} INFO - Started process (PID=3385) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:30:34.248+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:30:34.249+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:30:34.249+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:30:34.272+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:30:34.269+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:30:34.274+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:30:34.312+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.071 seconds
[2024-04-29T15:31:04.959+0000] {processor.py:161} INFO - Started process (PID=3445) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:31:04.961+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:31:04.964+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:31:04.964+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:31:05.002+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:31:04.997+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:31:05.004+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:31:05.084+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.166 seconds
[2024-04-29T15:31:35.167+0000] {processor.py:161} INFO - Started process (PID=3503) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:31:35.169+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:31:35.176+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:31:35.176+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:31:35.192+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:31:35.188+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:31:35.193+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:31:35.219+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.060 seconds
[2024-04-29T15:32:05.811+0000] {processor.py:161} INFO - Started process (PID=3560) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:32:05.812+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:32:05.815+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:32:05.814+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:32:05.837+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:32:05.832+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:32:05.839+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:32:05.860+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.058 seconds
[2024-04-29T15:32:36.644+0000] {processor.py:161} INFO - Started process (PID=3619) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:32:36.645+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:32:36.649+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:32:36.648+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:32:36.691+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:32:36.667+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:32:36.692+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:32:37.341+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.706 seconds
[2024-04-29T15:33:08.296+0000] {processor.py:161} INFO - Started process (PID=3678) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:33:08.297+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:33:08.300+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:33:08.299+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:33:08.318+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:33:08.314+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:33:08.319+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:33:08.340+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.052 seconds
[2024-04-29T15:33:38.453+0000] {processor.py:161} INFO - Started process (PID=3738) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:33:38.455+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:33:38.458+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:33:38.457+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:33:38.486+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:33:38.470+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:33:38.487+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:33:38.514+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.069 seconds
[2024-04-29T15:34:09.080+0000] {processor.py:161} INFO - Started process (PID=3796) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:34:09.082+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:34:09.084+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:34:09.083+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:34:09.097+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:34:09.094+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:34:09.099+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:34:09.128+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.054 seconds
[2024-04-29T15:34:39.559+0000] {processor.py:161} INFO - Started process (PID=3855) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:34:39.560+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:34:39.562+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:34:39.562+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:34:39.578+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:34:39.574+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:34:39.579+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:34:39.603+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.049 seconds
[2024-04-29T15:35:10.245+0000] {processor.py:161} INFO - Started process (PID=3913) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:35:10.247+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:35:10.249+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:35:10.249+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:35:10.264+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:35:10.260+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:35:10.265+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:35:10.287+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.049 seconds
[2024-04-29T15:35:41.093+0000] {processor.py:161} INFO - Started process (PID=3972) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:35:41.094+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:35:41.096+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:35:41.096+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:35:41.112+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:35:41.109+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:35:41.114+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:35:41.135+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.049 seconds
[2024-04-29T15:36:11.461+0000] {processor.py:161} INFO - Started process (PID=4031) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:36:11.462+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:36:11.464+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:36:11.464+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:36:11.480+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:36:11.476+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:36:11.481+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:36:11.503+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.049 seconds
[2024-04-29T15:36:41.670+0000] {processor.py:161} INFO - Started process (PID=4090) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:36:41.672+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:36:41.677+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:36:41.676+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:36:41.712+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:36:41.703+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:36:41.713+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:36:41.756+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.096 seconds
[2024-04-29T15:37:12.485+0000] {processor.py:161} INFO - Started process (PID=4148) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:37:12.487+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:37:12.494+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:37:12.491+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:37:12.819+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:37:12.600+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:37:12.823+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:37:12.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.436 seconds
[2024-04-29T15:37:43.521+0000] {processor.py:161} INFO - Started process (PID=4207) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:37:43.522+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:37:43.526+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:37:43.525+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:37:43.549+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:37:43.544+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:37:43.550+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:37:43.576+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.061 seconds
[2024-04-29T15:38:13.936+0000] {processor.py:161} INFO - Started process (PID=4267) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:38:13.937+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:38:13.939+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:38:13.939+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:38:13.957+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:38:13.952+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:38:13.959+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:38:13.985+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.058 seconds
[2024-04-29T15:38:44.628+0000] {processor.py:161} INFO - Started process (PID=4326) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:38:44.630+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:38:44.632+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:38:44.631+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:38:44.646+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:38:44.642+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:38:44.647+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:38:44.666+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.046 seconds
[2024-04-29T15:39:14.857+0000] {processor.py:161} INFO - Started process (PID=4385) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:39:14.858+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:39:14.862+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:39:14.861+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:39:14.879+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:39:14.874+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:39:14.880+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:39:14.903+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.054 seconds
[2024-04-29T15:39:45.086+0000] {processor.py:161} INFO - Started process (PID=4444) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:39:45.087+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:39:45.092+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:39:45.092+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:39:45.113+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:39:45.107+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:39:45.115+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:39:45.141+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.062 seconds
[2024-04-29T15:40:15.649+0000] {processor.py:161} INFO - Started process (PID=4504) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:40:15.663+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:40:15.668+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:40:15.668+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:40:15.709+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:40:15.699+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:40:15.711+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:40:15.738+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.096 seconds
[2024-04-29T15:40:46.229+0000] {processor.py:161} INFO - Started process (PID=4563) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:40:46.231+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:40:46.234+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:40:46.233+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:40:46.261+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:40:46.258+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:40:46.262+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:40:46.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.070 seconds
[2024-04-29T15:41:16.411+0000] {processor.py:161} INFO - Started process (PID=4623) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:41:16.413+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:41:16.417+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:41:16.416+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:41:16.437+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:41:16.433+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:41:16.439+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:41:16.461+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.057 seconds
[2024-04-29T15:41:46.752+0000] {processor.py:161} INFO - Started process (PID=4681) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:41:46.753+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:41:46.755+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:41:46.755+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:41:46.767+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:41:46.764+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:41:46.768+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:41:46.787+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.040 seconds
[2024-04-29T15:42:17.030+0000] {processor.py:161} INFO - Started process (PID=4740) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:42:17.031+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:42:17.033+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:42:17.033+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:42:17.047+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:42:17.043+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:42:17.048+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:42:17.065+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.040 seconds
[2024-04-29T15:42:47.373+0000] {processor.py:161} INFO - Started process (PID=4799) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:42:47.374+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:42:47.376+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:42:47.376+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:42:47.389+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:42:47.385+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:42:47.390+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:42:47.445+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.081 seconds
[2024-04-29T15:43:17.695+0000] {processor.py:161} INFO - Started process (PID=4857) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:43:17.696+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:43:17.699+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:43:17.698+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:43:17.713+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:43:17.710+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 6, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:43:17.715+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:43:17.736+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.047 seconds
[2024-04-29T15:43:37.039+0000] {processor.py:161} INFO - Started process (PID=4901) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:43:37.040+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:43:37.043+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:43:37.042+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:43:37.074+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:43:37.069+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:43:37.079+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:43:37.105+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.072 seconds
[2024-04-29T15:43:53.634+0000] {processor.py:161} INFO - Started process (PID=4933) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:43:53.635+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:43:53.640+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:43:53.639+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:43:53.743+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:43:53.738+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:43:53.745+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:43:53.776+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.154 seconds
[2024-04-29T15:44:36.267+0000] {processor.py:161} INFO - Started process (PID=4986) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:44:36.283+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:44:36.293+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:44:36.293+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:44:36.337+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:44:36.320+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:44:36.339+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:44:36.389+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.131 seconds
[2024-04-29T15:45:06.442+0000] {processor.py:161} INFO - Started process (PID=5045) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:45:06.444+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:45:06.450+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:45:06.449+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:45:06.475+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:45:06.471+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:45:06.476+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:45:06.510+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.076 seconds
[2024-04-29T15:45:36.838+0000] {processor.py:161} INFO - Started process (PID=5104) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:45:36.839+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:45:36.841+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:45:36.841+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:45:36.871+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:45:36.864+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:45:36.872+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:45:36.916+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.084 seconds
[2024-04-29T15:46:07.306+0000] {processor.py:161} INFO - Started process (PID=5162) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:46:07.308+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:46:07.344+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:46:07.333+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:46:07.401+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:46:07.384+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:46:07.405+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:46:07.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.168 seconds
[2024-04-29T15:46:37.789+0000] {processor.py:161} INFO - Started process (PID=5221) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:46:37.791+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:46:37.794+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:46:37.793+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:46:37.809+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:46:37.805+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:46:37.811+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:46:37.831+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.048 seconds
[2024-04-29T15:47:08.588+0000] {processor.py:161} INFO - Started process (PID=5277) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:47:08.589+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:47:08.591+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:47:08.591+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:47:08.607+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:47:08.603+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:47:08.608+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:47:08.630+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.049 seconds
[2024-04-29T15:47:39.248+0000] {processor.py:161} INFO - Started process (PID=5336) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:47:39.249+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:47:39.251+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:47:39.251+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:47:39.443+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:47:39.426+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:47:39.444+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:47:39.771+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.532 seconds
[2024-04-29T15:48:10.024+0000] {processor.py:161} INFO - Started process (PID=5395) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:48:10.026+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:48:10.046+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:48:10.028+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:48:10.085+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:48:10.076+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:48:10.087+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:48:10.215+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.213 seconds
[2024-04-29T15:50:39.356+0000] {processor.py:161} INFO - Started process (PID=5424) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:50:39.358+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:50:39.360+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:50:39.359+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:50:39.383+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:50:39.378+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:50:39.385+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:50:39.422+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.080 seconds
[2024-04-29T15:51:09.775+0000] {processor.py:161} INFO - Started process (PID=5480) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:51:09.777+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:51:09.787+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:51:09.778+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:51:09.849+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:51:09.828+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:51:09.851+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:51:09.904+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.140 seconds
[2024-04-29T15:51:50.625+0000] {processor.py:161} INFO - Started process (PID=5518) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:51:50.626+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:51:50.627+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:51:50.627+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:51:50.714+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:51:50.704+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:51:50.716+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:51:50.747+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.130 seconds
[2024-04-29T15:52:24.943+0000] {processor.py:161} INFO - Started process (PID=5575) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T15:52:24.945+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T15:52:24.948+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:52:24.946+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T15:52:24.972+0000] {logging_mixin.py:188} INFO - [2024-04-29T15:52:24.964+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from data_lake_builder import DataLakeBuilder
ModuleNotFoundError: No module named 'data_lake_builder'
[2024-04-29T15:52:24.974+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T15:52:35.044+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 843, in process_file
    DagFileProcessor.update_import_errors(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 622, in update_import_errors
    existing_import_error_files = [x.filename for x in session.query(errors.ImportError.filename).all()]
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-04-29T16:07:18.735+0000] {processor.py:161} INFO - Started process (PID=26) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:07:18.738+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:07:18.743+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:07:18.741+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:07:18.861+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:07:18.850+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from ..data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:07:18.866+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:07:18.970+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.245 seconds
[2024-04-29T16:07:49.101+0000] {processor.py:161} INFO - Started process (PID=85) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:07:49.102+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:07:49.104+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:07:49.104+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:07:49.118+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:07:49.113+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from ..data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:07:49.119+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:07:49.143+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.049 seconds
[2024-04-29T16:08:19.427+0000] {processor.py:161} INFO - Started process (PID=144) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:08:19.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:08:19.430+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:08:19.430+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:08:19.455+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:08:19.449+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from ..data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:08:19.457+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:08:19.495+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.083 seconds
[2024-04-29T16:08:49.807+0000] {processor.py:161} INFO - Started process (PID=202) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:08:49.808+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:08:49.813+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:08:49.810+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:08:49.829+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:08:49.826+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from ..data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:08:49.831+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:08:49.887+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.089 seconds
[2024-04-29T16:09:20.144+0000] {processor.py:161} INFO - Started process (PID=261) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:09:20.145+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:09:20.147+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:09:20.147+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:09:20.161+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:09:20.157+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from ..data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:09:20.162+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:09:20.215+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.077 seconds
[2024-04-29T16:09:51.176+0000] {processor.py:161} INFO - Started process (PID=320) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:09:51.178+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:09:51.186+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:09:51.181+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:09:51.250+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:09:51.240+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from ..data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:09:51.251+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:10:01.309+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 843, in process_file
    DagFileProcessor.update_import_errors(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 622, in update_import_errors
    existing_import_error_files = [x.filename for x in session.query(errors.ImportError.filename).all()]
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-04-29T16:10:32.308+0000] {processor.py:161} INFO - Started process (PID=379) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:10:32.310+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:10:32.330+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:10:32.327+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:10:32.403+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:10:32.384+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from ..data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:10:32.406+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:10:32.497+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.219 seconds
[2024-04-29T16:11:03.525+0000] {processor.py:161} INFO - Started process (PID=438) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:11:03.527+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:11:03.532+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:11:03.530+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:11:03.554+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:11:03.546+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from ..data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:11:03.556+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:11:03.584+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.071 seconds
[2024-04-29T16:11:34.102+0000] {processor.py:161} INFO - Started process (PID=497) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:11:34.103+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:11:34.107+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:11:34.105+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:11:34.133+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:11:34.122+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from ..data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:11:34.135+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:11:34.199+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.111 seconds
[2024-04-29T16:12:04.659+0000] {processor.py:161} INFO - Started process (PID=556) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:12:04.661+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:12:04.663+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:12:04.663+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:12:04.679+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:12:04.673+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from ..data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:12:04.680+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:12:04.704+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.053 seconds
[2024-04-29T16:12:35.016+0000] {processor.py:161} INFO - Started process (PID=615) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:12:35.017+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:12:35.019+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:12:35.019+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:12:35.029+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:12:35.026+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from ..data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:12:35.030+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:12:35.049+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.040 seconds
[2024-04-29T16:14:29.144+0000] {processor.py:161} INFO - Started process (PID=658) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:14:29.147+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:14:29.155+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:14:29.149+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:14:29.203+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:14:29.184+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from ..data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:14:29.207+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:14:29.266+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.151 seconds
[2024-04-29T16:14:59.520+0000] {processor.py:161} INFO - Started process (PID=717) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:14:59.521+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:14:59.523+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:14:59.523+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:14:59.558+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:14:59.551+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from ..data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:14:59.560+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:14:59.605+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.093 seconds
[2024-04-29T16:15:29.685+0000] {processor.py:161} INFO - Started process (PID=774) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:15:29.690+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:15:29.692+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:15:29.692+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:15:29.714+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:15:29.708+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from ..data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:15:29.715+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:15:29.737+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.061 seconds
[2024-04-29T16:16:01.399+0000] {processor.py:161} INFO - Started process (PID=827) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:16:01.722+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:16:02.297+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:16:01.909+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:16:03.293+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:16:03.124+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from ..data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:16:03.336+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:16:04.997+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 4.484 seconds
[2024-04-29T16:16:35.966+0000] {processor.py:161} INFO - Started process (PID=885) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:16:35.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:16:35.971+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:16:35.970+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:16:36.042+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:16:35.980+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from ..data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:16:36.044+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:16:36.551+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.591 seconds
[2024-04-29T16:17:07.252+0000] {processor.py:161} INFO - Started process (PID=943) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:17:07.253+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:17:07.257+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:17:07.254+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:17:07.272+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:17:07.267+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from ..data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:17:07.273+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:17:07.321+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.076 seconds
[2024-04-29T16:17:37.878+0000] {processor.py:161} INFO - Started process (PID=1003) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:17:37.880+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:17:37.884+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:17:37.881+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:17:37.909+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:17:37.902+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from ..data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:17:37.916+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:17:37.979+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.111 seconds
[2024-04-29T16:18:09.160+0000] {processor.py:161} INFO - Started process (PID=1063) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:18:09.173+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:18:09.177+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:18:09.174+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:18:09.244+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:18:09.235+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from ..data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:18:09.252+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:18:09.891+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.752 seconds
[2024-04-29T16:18:39.990+0000] {processor.py:161} INFO - Started process (PID=1122) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:18:39.991+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:18:39.993+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:18:39.992+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:18:40.015+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:18:40.007+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from ..data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:18:40.017+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:18:40.039+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.057 seconds
[2024-04-29T16:20:49.407+0000] {processor.py:161} INFO - Started process (PID=1136) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:20:49.422+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:20:49.424+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:20:49.423+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:20:49.508+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:20:49.487+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from ..data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:20:49.511+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:20:51.036+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 1.644 seconds
[2024-04-29T16:21:21.552+0000] {processor.py:161} INFO - Started process (PID=1194) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:21:21.554+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:21:21.556+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:21:21.555+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:21:21.576+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:21:21.571+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from ..data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:21:21.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:21:21.660+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.130 seconds
[2024-04-29T16:29:10.673+0000] {processor.py:161} INFO - Started process (PID=1203) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:29:10.776+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:29:12.820+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:29:12.271+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:29:15.888+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:29:14.923+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:29:16.540+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:29:35.831+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 843, in process_file
    DagFileProcessor.update_import_errors(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 622, in update_import_errors
    existing_import_error_files = [x.filename for x in session.query(errors.ImportError.filename).all()]
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-04-29T16:36:42.559+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:36:42.575+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:36:42.609+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:36:42.600+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:36:42.884+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:36:42.868+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:36:42.886+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:36:43.608+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 1.179 seconds
[2024-04-29T16:37:23.287+0000] {processor.py:161} INFO - Started process (PID=98) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:37:23.309+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:37:23.313+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:37:23.312+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:37:23.534+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:37:23.502+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:37:23.536+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:37:23.739+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.465 seconds
[2024-04-29T16:37:54.771+0000] {processor.py:161} INFO - Started process (PID=154) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:37:54.775+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:37:54.782+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:37:54.779+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:37:54.916+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:37:54.881+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:37:54.918+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:37:54.995+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.235 seconds
[2024-04-29T16:38:25.728+0000] {processor.py:161} INFO - Started process (PID=213) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:38:25.730+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:38:25.734+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:38:25.733+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:38:25.776+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:38:25.767+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:38:25.778+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:38:25.876+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.155 seconds
[2024-04-29T16:38:56.784+0000] {processor.py:161} INFO - Started process (PID=272) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:38:56.786+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:38:56.788+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:38:56.787+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:38:56.801+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:38:56.797+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:38:56.803+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:38:56.824+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.051 seconds
[2024-04-29T16:39:27.171+0000] {processor.py:161} INFO - Started process (PID=331) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:39:27.176+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:39:27.181+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:39:27.181+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:39:27.250+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:39:27.247+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:39:27.252+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:39:27.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.141 seconds
[2024-04-29T16:39:57.775+0000] {processor.py:161} INFO - Started process (PID=390) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:39:57.776+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:39:57.778+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:39:57.778+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:39:57.789+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:39:57.787+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:39:57.791+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:39:57.813+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.047 seconds
[2024-04-29T16:40:28.770+0000] {processor.py:161} INFO - Started process (PID=449) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:40:28.771+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:40:28.773+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:40:28.772+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:40:28.785+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:40:28.782+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:40:28.786+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:40:28.807+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.044 seconds
[2024-04-29T16:40:59.107+0000] {processor.py:161} INFO - Started process (PID=508) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:40:59.108+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:40:59.110+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:40:59.109+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:40:59.122+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:40:59.120+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:40:59.123+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:40:59.143+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.043 seconds
[2024-04-29T16:41:29.400+0000] {processor.py:161} INFO - Started process (PID=567) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:41:29.401+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:41:29.403+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:41:29.403+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:41:29.418+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:41:29.415+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:41:29.419+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:41:29.448+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.057 seconds
[2024-04-29T16:41:59.775+0000] {processor.py:161} INFO - Started process (PID=626) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:41:59.776+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:41:59.778+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:41:59.778+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:41:59.797+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:41:59.793+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:41:59.798+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:41:59.820+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.052 seconds
[2024-04-29T16:42:30.596+0000] {processor.py:161} INFO - Started process (PID=685) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:42:30.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:42:30.604+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:42:30.604+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:42:30.616+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:42:30.613+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:42:30.617+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:42:30.638+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.051 seconds
[2024-04-29T16:43:00.906+0000] {processor.py:161} INFO - Started process (PID=745) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:43:00.908+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:43:00.910+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:43:00.909+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:43:00.931+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:43:00.927+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:43:00.932+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:43:00.952+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.052 seconds
[2024-04-29T16:43:31.353+0000] {processor.py:161} INFO - Started process (PID=804) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:43:31.354+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:43:31.357+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:43:31.356+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:43:31.401+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:43:31.368+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:43:31.404+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:43:31.431+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.092 seconds
[2024-04-29T16:44:01.965+0000] {processor.py:161} INFO - Started process (PID=864) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:44:01.966+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:44:01.968+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:44:01.968+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:44:01.984+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:44:01.977+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:44:01.985+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:44:02.017+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.062 seconds
[2024-04-29T16:44:32.606+0000] {processor.py:161} INFO - Started process (PID=923) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:44:32.607+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:44:32.609+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:44:32.608+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:44:32.618+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:44:32.615+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:44:32.621+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:44:33.522+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.921 seconds
[2024-04-29T16:45:04.496+0000] {processor.py:161} INFO - Started process (PID=982) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:45:04.497+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:45:04.500+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:45:04.500+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:45:04.512+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:45:04.510+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:45:04.513+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:45:04.533+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.042 seconds
[2024-04-29T16:45:35.451+0000] {processor.py:161} INFO - Started process (PID=1041) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:45:35.452+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:45:35.454+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:45:35.454+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:45:35.466+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:45:35.463+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:45:35.467+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:45:35.487+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.041 seconds
[2024-04-29T16:46:05.834+0000] {processor.py:161} INFO - Started process (PID=1100) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:46:05.835+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:46:05.837+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:46:05.837+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:46:05.857+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:46:05.848+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:46:05.859+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:46:05.879+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.052 seconds
[2024-04-29T16:46:36.835+0000] {processor.py:161} INFO - Started process (PID=1160) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:46:36.836+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:46:36.838+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:46:36.838+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:46:36.849+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:46:36.846+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:46:36.850+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:46:36.869+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.041 seconds
[2024-04-29T16:47:07.728+0000] {processor.py:161} INFO - Started process (PID=1218) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:47:07.729+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:47:07.731+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:47:07.731+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:47:07.744+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:47:07.740+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:47:07.745+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:47:07.768+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.047 seconds
[2024-04-29T16:47:38.381+0000] {processor.py:161} INFO - Started process (PID=1277) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:47:38.382+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:47:38.385+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:47:38.384+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:47:38.398+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:47:38.394+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:47:38.399+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:47:38.429+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.054 seconds
[2024-04-29T16:48:08.547+0000] {processor.py:161} INFO - Started process (PID=1336) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:48:08.548+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:48:08.550+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:48:08.549+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:48:08.562+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:48:08.559+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:48:08.563+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:48:08.585+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.045 seconds
[2024-04-29T16:48:38.986+0000] {processor.py:161} INFO - Started process (PID=1395) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:48:38.987+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:48:38.994+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:48:38.993+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:48:39.032+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:48:39.021+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:48:39.039+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:48:39.106+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.127 seconds
[2024-04-29T16:49:09.556+0000] {processor.py:161} INFO - Started process (PID=1454) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:49:09.558+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:49:09.560+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:49:09.560+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:49:09.577+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:49:09.574+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:49:09.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:49:09.612+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.066 seconds
[2024-04-29T16:49:39.801+0000] {processor.py:161} INFO - Started process (PID=1514) to work on /opt/airflow/dags/pipeline.py
[2024-04-29T16:49:39.802+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2024-04-29T16:49:39.804+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:49:39.803+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2024-04-29T16:49:39.816+0000] {logging_mixin.py:188} INFO - [2024-04-29T16:49:39.812+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 7, in <module>
    from .data_lake_builder import DataLakeBuilder
ImportError: attempted relative import with no known parent package
[2024-04-29T16:49:39.817+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2024-04-29T16:49:39.839+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipeline.py took 0.044 seconds
