[2024-04-15T14:53:18.512+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T14:53:18.553+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: calculator_dag.calculate_sum scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T14:53:18.564+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: calculator_dag.calculate_sum scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T14:53:18.564+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 6
[2024-04-15T14:53:18.582+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): calculate_sum> on 2024-04-14 00:00:00+00:00
[2024-04-15T14:53:18.604+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'calculator_dag', 'calculate_sum', 'scheduled__2024-04-14T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/calculator_dag.py', '--cfg-path', '/tmp/tmp69594ojg']
[2024-04-15T14:53:18.608+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask calculate_sum
[2024-04-15T14:53:18.604+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=732) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T14:53:18.609+0000] {standard_task_runner.py:63} INFO - Started process 734 to run task
[2024-04-15T14:53:18.690+0000] {task_command.py:426} INFO - Running <TaskInstance: calculator_dag.calculate_sum scheduled__2024-04-14T00:00:00+00:00 [running]> on host ead826da457c
[2024-04-15T14:53:18.833+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yazid' AIRFLOW_CTX_DAG_ID='calculator_dag' AIRFLOW_CTX_TASK_ID='calculate_sum' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-14T00:00:00+00:00'
[2024-04-15T14:53:18.839+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T14:53:18.854+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T14:53:18.856+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/calculator_dag.py", line 16, in calculate_sum
    if not all(isinstance(angka, int) and angka.isnumeric() for angka in angka_acak):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/calculator_dag.py", line 16, in <genexpr>
    if not all(isinstance(angka, int) and angka.isnumeric() for angka in angka_acak):
                                          ^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'isnumeric'
[2024-04-15T14:53:18.875+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=calculator_dag, task_id=calculate_sum, execution_date=20240414T000000, start_date=20240415T145318, end_date=20240415T145318
[2024-04-15T14:53:18.909+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 15 for task calculate_sum ('int' object has no attribute 'isnumeric'; 734)
[2024-04-15T14:53:18.945+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-15T14:53:18.980+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T14:53:18.984+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
