[2024-04-16T12:37:05.727+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: eksplorasi.create_fruits_table scheduled__2023-03-11T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
